permalink: /:year/:month/:day/:title.html
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "org"]
highlighter: rouge

markdown: kramdown

title : TBlog
author :
name : Tubo
email : yangyingchao@gmail.com
github : yangyingchao

rss_url: /pages/feed.xml


production_url : http://yangyingchao.github.io

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# Social account
twitter:
# weibo:    ID
# codepen:  username
# dribbble: username


# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
sass:
style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
