future: true
url: http://yangyingchao.github.io

title : TBlog
# author :
name : TBlog
email : yangyingchao@gmail.com
github : yangyingchao

plugins:
  - jekyll-paginate

# paginate: 5
# paginate_path: "page:num"

highlighter: rouge
truncate: true

