future: true
permalink: /:title/
url: http://yangyingchao.github.io

title : TBlog
author :
name : TBlog
email : yangyingchao@gmail.com
github : yangyingchao

paginate: 20
highlighter: rouge
truncate: true
