#+TITLE: Chrome Extension Overview 笔记
#+AUTHOR: Yang, Ying-chao
#+EMAIL:  yangyingchao[at]gmail[dot]com
#+OPTIONS: ^:nil toc:1
#+KEYWORDS: (nil)
#+KEYWORDS: extension, chrome
#+CATEGORY: Web
#+DESCRIPTION: Chrome Extension Overview 笔记，省得忘。。
#+OPTIONS:    H:3 \n:nil ::t |:t ^:{} -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align nodlcheck hidestars oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+LANGUAGE:   en
#+HTML_HEAD:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    http://yangyingchao.github.io
#+LINK_HOME:  http://yangyingchao.github.io
#+EXCLUDE_TAGS: noexport

记录一下 阅读 chrome extension 的笔记，原文地址：[[https://developer.chrome.com/extensions/overview]].

* 基础

 Chrome 扩展实际上是打包在一起的一个文件集合，包括： HTML, CSS, JavaScript, images 等
 等。这些文件组成的扩展用于向浏览器增加新的功能。 Chrome 扩展本质上就是网页，可以使用
 从 =XMLHttpRequest= , =json= ,  =HTML5= 等所有的浏览器提供的 API。

* 文件

Chrome 扩展有如下的文件：

 - 一个 Manifest File
 - 一个或多个的 HTML 文件
 - （可选） 一个或多个的 =JavaScript= 文件
 - （可选） 任何其他的所需文件，如图片等

扩展开发的时候，将所有文件放在一个目录下，Chrome 可以从该目录下加载开发中的插件。开
发完成之后，其中的所有文件会被打包成一个扩展名为 =.rts= ZIP 包。

** Manifest 文件

Manifest 文件用于向浏览器提供扩展的基本信息，比如文件以及兼容性等。下面是一个典型的
Manifest 文件：

#+BEGIN_SRC js -r -n
  {
    "name": "My Extension",
    "version": "2.1",
    "description": "Gets information from Google.",
    "icons": { "128": "icon_128.png" },
    "background": {
      "persistent": false,
      "scripts": ["bg.js"]
    },
    "permissions": ["http://*.google.com/", "https://*.google.com/"],
    "browser_action": {
      "default_title": "",
      "default_icon": "icon_19.png",
      "default_popup": "popup.html"
    }
  }
#+END_SRC

Manifest 的具体细节，参考：[[https://developer.chrome.com/extensions/manifest]].

* 框架

扩展的大概组成如下：

- /后台页/ ( /background page/ ) ： 不可见但包含了该扩展主要逻辑的页面。
- /UI Pages/ ： 用于展示扩展提供的某些内容。
- /Content Script/ ： 用于与加载的网页交互的 JS 脚本。


** [[https://developer.chrome.com/extensions/background_pages][Background Page]]

后台页包含了扩展的主要逻辑。根据后台页是否始终打开，分为两种：

- Persistent background pages : 始终打开
- Event Pages: 按需打开和关闭.

** UI Pages

扩展可以有多个 UI Pages，例如：

 - /Popup page/: 用于 BrowserActions。
 - /Options/ : 用于更改选项。

同一扩展中的 UI Pages 可以访问其他 UI Pages 的 DOM。

** Content Scripts

扩展通过 Content Scripts 与网页交互，它由 JavaScript 组成，并在加载网页时候执行。
Content Scripts 可以访问网页的 DOM，但是无法更改 background page 的 DOM。

 Content Scripts 通过消息与后台页以及其他 UI Pages 交互。

 #+BEGIN_SRC ditaa :file ../assets/img/chrome_extention_components.png  :cmdline -r -s 0.8
          +--------------------------------------------------------------+
          |             Parent Extension                                 |
          |                                                              |
          |                                                              |
          |    +------------------------+             +--------------+   |
          |    |                        | <---------> | popup.html   |   |
          |    |                        |             +--------------+   |
          |    |                        |                    ^           |
          |    |                        |                    |           |
          |    |                        |                    v           |
          |    |  Background.html       |             +------------+     |
          |    |                        | <---------> | UI_Pages   |     |
          |    +------------------------+             +------------+     |
          |                         ^                                    |
          |                         |                                    |
          +-------------------------:------------------------------------+
                                    :
                                    |
                                    |
                                    |Messages
                                    |
                                    |
                                    |
                       +------------+---------+
                       |   ContentScript.js   |
                       +------------+---------+
                                    |
                                    |
                                    |
                                    v
                        +---------------------+
                        |       Web Page      |
                        +---------------------+

 #+END_SRC

* 使用 Chrome API

 Chrome 为扩展提供了以 =chrome.= 开头的 Chrome API，用于让扩展和浏览器合作的更紧密。


** 同步与异步

*** 异步 API
=chrome.*= 的 API 大多为异步 API：该类型 API 调用时候会直接返回，执行的结果将通过注册
的回调通知给扩展。

#+BEGIN_SRC js -r -n
chrome.tabs.create(object createProperties, function callback)
#+END_SRC

*** 同步 API
有些 API 为同步 API，不需要回调，该类 API 在结果返回之前会阻塞。例如：
#+BEGIN_SRC js -r -n
string chrome.runtime.getURL()
#+END_SRC

* 页面之间的交互

 扩展的页面间可以直接相互交互，=chrome.extension= 提供了 =getViews()= 和
 =getBackgroundPage()= 用于获取某个 Page 和后台页。

* 数据的存储

 插件可以通过 [[https://developer.chrome.com/extensions/storage][Storage API]] 或者 HTML5 的 [[http://dev.w3.org/html5/webstorage/][Web Storage API]] 来存储数据。但如果扩展处于匿名
 模式 (incognito mode)，则无法存储数据，可以通过相关的 Tab 或者 Window 的 =incognito=
 属性来检查插件是否处于匿名状态：

 #+BEGIN_SRC js -r -n
   function saveTabData(tab, data) {
     if (tab.incognito) {
       chrome.runtime.getBackgroundPage(function(bgPage) {
         bgPage[tab.url] = data;      // Persist data ONLY in memory
       });
     } else {
       localStorage[tab.url] = data;  // OK to store data
     }
   }
 #+END_SRC
