#+TITLE: C++ 二进制兼容性
#+AUTHOR: Yang, Ying-chao
#+EMAIL:  yangyingchao[at]gmail[dot]com
#+KEYWORDS: Binary Compatibility
#+CATEGORY: C/C++
#+OPTIONS:  ^:nil toc:1 H:3 \n:nil ::t |:t ^:{} -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align nodlcheck oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+LANGUAGE:   en
#+HTML_HEAD: <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    http://yangyingchao.github.io
#+LINK_HOME:  http://yangyingchao.github.io
#+EXCLUDE_TAGS: noexport

前两天扫了一眼 JNI 的一部分代码，被长达 22 个参数的函数着实震惊了一把，
而且从文件历史上看，参数个数近来仍在增长中。每次增长之后，一旦 Java 代码和 C
库不匹配，App 总是直接 Crash 掉。这个问题的解决办法暂且不谈，但它让我想起了另
外一个问题：[[https://techbase.kde.org/Policies/Binary_Compatibility_Issues_With_C++][二进制兼容性 (Binary Compatibility)]]。摘录一下。

* 二进制兼容与源代码兼容
如果一个应用程序动态链接到一个共享库，并且该库更新之后，应用程序无需重新编译即
可继续使用，则该动态库具有 *二进制兼容性 (Binary Compatibility)* 。

相对的，如果应用程序需要重新编译才能运行，则该库具有 *源代码兼容性 (Source
Code Compatibility)*

而如果应用程序必须修改源代码才能编译运行，通常我们称其为不兼容。

* The Do's and Don'ts

简单来说，如果修改了某些个类，但是这些修改并没有改变类实例的内存布局
（实例大小以及类的虛函数表 (Virtual Function Table)） ，
则该改动通常具有二进制兼容性，反之则不具备。

** The Do's

下列操作通常不会引起二进制兼容问题：

 - 增加新的非虛成员函数

 - 为类增加新的静态方法

 - 为一个类增加新的枚举类型

 - 为枚举类型添加新的定义\\
   这里有个极端的情况：新定义的值过大导致编译器重新为枚举选择新的基本类型 (Underlying Type)。
   这会导致库文件以及引用了该枚举的类的内存布局的变化，从而导致不兼容。

 - 子类中重载父类的虚函数


** The Don'ts