#+TITLE: C Printf Format
#+AUTHOR: Yang, Ying-chao
#+EMAIL:      yangyingchao[at]gmail[dot]com
#+OPTIONS: ^:nil toc:2
#+KEYWORDS: (nil)
#+CATEGORY: Cfamily
#+DESCRIPTION: (nil)
#+OPTIONS:    H:3 toc:2 \n:nil ::t |:t ^:{} -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align fold nodlcheck hidestars oddeven lognotestate hideblocks
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+LANGUAGE:   en
#+HTML_HEAD:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    http://yangyingchao.github.io
#+LINK_HOME:  http://yangyingchao.github.io
#+EXCLUDE_TAGS: noexport

* printf family format:
:PROPERTIES:
:CUSTOM_ID: h:EB7C1B38-0CA5-4D4E-98AC-EF916E58199B
:END:


[[sec:one][=ordinary characters=]] + [[sec:conversion][=conversion sepcifications=]]


   <<sec:one>>
 * *Ordinary Characters* \\
   /ordinary characters/ (not %), are copied unchanged to the output stream.

  <<sec:conversion>>
 * *Conversion Specifications* \\
   Each /specification/ results in  fetching  zero  or   more  subsequent  arguments.

   Conversion specification is introduced by:

    [[sec:f][=%=]] + [[sec:flags][=flags=]] + [[sec:field][=field width=]] + [[sec:precision][=precision=]] + [[sec:length][=length modifier=]] + [[sec:cs][=conversion specifier=]]

   <<sec:f>>
   - *%* \\
     Mark of the start of an /convertion specifier/

   <<sec:flags>>
   - *flags*
     =%= 之后可以有 0 或多个 flags。

     + =#=    The value  should be converted to  an "alternate form". \\

       * For =o=  conversions\\
         the first character of the output string is made zero (by prefixing a 0 if it
         was not zero already).

       * For  =x=  and =X=  conversions\\
         a nonzero result has the string "0x" (or "0X" for X conversions) prepended to
       it.

       * For =a=,  =A=,  =e=, =E=,  =f=, =F=,  =g=, and  =G= conversions\\
         The result will always contain a decimal point, even if no digits follow it
       (normally, a decimal point appears in the results of those conversions only if
       a digit follows). For =g= and =G= conversions, trailing zeros are not removed from
       the result as they would otherwise be. For other conversions, the result is
       undefined.

     + =0=\\
       The value should be zero padded.  For d, i, o, u, x, X,
          a, A, e,  E, f, F, g, and G  conversions, the converted
          value  is padded  on the  left with  zeros rather  than
          blanks.  If the  0 and - flags both appear,  the 0 flag
          is ignored.   If a  precision is  given with  a numeric
          conversion  (d, i,  o,  u, x,  and X),  the  0 flag  is
          ignored.   For  other   conversions,  the  behavior  is
          undefined.
     + =-= \\
       The converted value is to be left adjusted on the field
          boundary.  (The  default is right  justification.)  The
          converted  value is  padded on  the right  with blanks,
          rather  than on  the left  with blanks  or zeros.   A -
          overrides a 0 if both are given.
     + =SPACE=\\
       (a  space) A  blank should  be left  before a  positive
          number  (or   empty  string)   produced  by   a  signed
          conversion.
     + =+=\\
       A sign (+ or -) should always be placed before a number
          produced by a signed conversion.   By default a sign is
          used only for negative numbers.   A + overrides a space
          if both are used.


   <<sec:field>>
   - *field width* \\
          An optional decimal digit  string (with nonzero first digit)
     specifying a  minimum field  width.  If the  converted value
     has fewer characters than the field width, it will be padded
     with spaces  on the left  (or right, if  the left-adjustment
     flag has been given).  Instead of a decimal digit string one
     may  write "*"  or "*m$"  (for  some decimal  integer m)  to
     specify that the field width  is given in the next argument,
     or in the m-th argument, respectively, which must be of type
     int.  A negative field width is taken as a '-' flag followed
     by a positive field width.  In no case does a nonexistent or
     small field width cause truncation of a field; if the result
     of a conversion is wider than  the field width, the field is
     expanded to contain the conversion result.

   <<sec:precision>>
   - *precision* \\
          An  optional  precision,  in  the form  of  a  period  ('.')
     followed by an optional decimal  digit string.  Instead of a
     decimal digit  string one may  write "*" or "*m$"  (for some
     decimal integer m) to specify that the precision is given in
     the next  argument, or  in the m-th  argument, respectively,
     which must  be of type  int.  If  the precision is  given as
     just '.',  the precision  is taken to  be zero.   A negative
     precision is taken  as if the precision  were omitted.  This
     gives the minimum number of digits to appear for d, i, o, u,
     x, and X  conversions, the number of digits  to appear after
     the radix  character for a, A,  e, E, f, and  F conversions,
     the  maximum  number  of  significant digits  for  g  and  G
     conversions,  or  the maximum  number  of  characters to  be
     printed from a string for s and S conversions.

   <<sec:length>>
   - *length modifier* \\
     Here, "integer  conversion" stands for =d=,  =i=, =o=, =u=, ==x=,  or =X=
     conversion.

     + =hh= \\
       A following integer conversion  corresponds to a signed
       char  or  unsigned  char  argument, or  a  following  n
       conversion corresponds  to a  pointer to a  signed char
       argument.

     + =h= \\
       A following  integer conversion corresponds to  a short
       int or  unsigned short int  argument, or a  following n
       conversion  corresponds to  a  pointer to  a short  int
       argument.

     + =l=\\
       A  following integer conversion corresponds  to a
       long int or unsigned long  int argument, or a following
       n conversion  corresponds to  a pointer  to a  long int
       argument, or a following  c conversion corresponds to a
       wint_t   argument,   or   a  following   s   conversion
       corresponds to a pointer to wchar_t argument.

     + =ll=   \\
       A following  integer conversion corresponds
          to a long long int  or unsigned long long int argument,
          or a following n conversion corresponds to a pointer to
          a long long int argument.

     + =L=\\
       A  following a,  A,  e, E,  f, F,  g,  or G  conversion
          corresponds  to a  long double  argument.  (C99  allows
          %LF, but SUSv2 does not.)  This is a synonym for ll.

     + =j=  \\
       A  following  integer   conversion  corresponds  to  an
          intmax_t  or  uintmax_t  argument,  or  a  following  n
          conversion  corresponds to  a  pointer  to an  intmax_t
          argument.

     + =z= \\
       A following integer conversion  corresponds to a size_t
          or  ssize_t  argument,  or  a  following  n  conversion
          corresponds to a pointer to a size_t argument.

     + =t= \\
      A  following   integer  conversion  corresponds   to  a
          ptrdiff_t  argument,   or  a  following   n  conversion
          corresponds to a pointer to a ptrdiff_t argument.


   <<sec:cs>>
   - *conversion specifier* \\
     A  character that  specifies the  type of  conversion to  be
     applied.  The conversion specifiers and their meanings are:

     + =d, i=\\
      The  int  argument  is   converted  to  signed  decimal
          notation.   The precision,  if any,  gives the  minimum
          number  of digits  that must  appear; if  the converted
          value requires fewer  digits, it is padded  on the left
          with zeros.   The default  precision is  1.  When  0 is
          printed  with an  explicit precision  0, the  output is
          empty.

     + =o, u, x, X=\\
       The  unsigned int  argument  is  converted to  unsigned
          octal   (o),   unsigned   decimal  (u),   or   unsigned
          hexadecimal (x and X) notation.  The letters abcdef are
          used for x conversions; the letters ABCDEF are used for
          X  conversions.   The  precision,  if  any,  gives  the
          minimum  number  of digits  that  must  appear; if  the
          converted value requires fewer  digits, it is padded on
          the left with zeros.  The default precision is 1.  When
          0 is printed  with an explicit precision  0, the output
          is empty.

     + =e, E=\\
       The  double argument  is rounded  and converted  in the
          style [-]d.ddde+/-dd  where there  is one  digit before
          the decimal-point  character and  the number  of digits
          after it is equal to the precision; if the precision is
          missing, it is taken as 6; if the precision is zero, no
          decimal-point character appears.   An E conversion uses
          the letter E (rather than e) to introduce the exponent.
          The exponent  always contains  at least two  digits; if
          the value is zero, the exponent is 00.

     + =f, F=\\
       The double argument is rounded and converted to decimal
          notation in  the style [-]ddd.ddd, where  the number of
          digits after  the decimal-point  character is  equal to
          the  precision  specification.   If  the  precision  is
          missing,  it  is  taken  as  6;  if  the  precision  is
          explicitly  zero, no  decimal-point character  appears.
          If a decimal point appears,  at least one digit appears
          before it.

          (SUSv2 does  not know about  F and says  that character
          string representations for infinity and NaN may be made
          available.  SUSv3 adds a  specification for F.  The C99
          standard  specifies   "[-]inf"  or   "[-]infinity"  for
          infinity, and a string starting  with "nan" for NaN, in
          the case of f conversion, and "[-]INF" or "[-]INFINITY"
          or "NAN*" in the case of F conversion.)

     + =g, G=\\
       The double argument is converted in  style f or e (or F
          or E  for G conversions).  The  precision specifies the
          number  of significant  digits.   If  the precision  is
          missing, 6 digits are given;  if the precision is zero,
          it is  treated as 1.  Style  e is used if  the exponent
          from its conversion is less  than -4 or greater than or
          equal  to the  precision.  Trailing  zeros are  removed
          from the fractional part of the result; a decimal point
          appears only if it is followed by at least one digit.

     + =a, A=\\
       (C99;  not  in  SUSv2,  but   added  in  SUSv3)  For  a
          conversion,  the   double  argument  is   converted  to
          hexadecimal notation (using the  letters abcdef) in the
          style [-]0xh.hhhhp+/-; for A  conversion the prefix 0X,
          the  letters ABCDEF,  and the  exponent separator  P is
          used.   There  is  one  hexadecimal  digit  before  the
          decimal point,  and the  number of  digits after  it is
          equal to the precision.  The default precision suffices
          for an  exact representation of  the value if  an exact
          representation  in  base  2  exists  and  otherwise  is
          sufficiently  large  to   distinguish  values  of  type
          double.   The   digit  before  the  decimal   point  is
          unspecified for nonnormalized  numbers, and nonzero but
          otherwise unspecified for normalized numbers.

     + =c=\\
       If  no  l modifier  is  present,  the int  argument  is
          converted  to  an  unsigned  char,  and  the  resulting
          character is written.  If an l modifier is present, the
          wint_t  (wide character)  argument  is  converted to  a
          multibyte  sequence   by  a  call  to   the  wcrtomb(3)
          function,  with  a  conversion state  starting  in  the
          initial state,  and the  resulting multibyte  string is
          written.

     + =s= \\
       If no l modifier is  present: The const char * argument
          is expected  to be a  pointer to an array  of character
          type (pointer to a  string).  Characters from the array
          are  written up  to (but  not including)  a terminating
          null byte ('\0'); if a  precision is specified, no more
          than the number specified  are written.  If a precision
          is  given,  no  null  byte  need  be  present;  if  the
          precision is not specified, or is greater than the size
          of the array, the array must contain a terminating null
          byte.

          If  an  l  modifier  is present:  The  const  wchar_t *
          argument is  expected to  be a pointer  to an  array of
          wide characters.   Wide characters  from the  array are
          converted to  multibyte characters  (each by a  call to
          the  wcrtomb(3)  function,   with  a  conversion  state
          starting  in the  initial state  before the  first wide
          character), up to and including a terminating null wide
          character.   The  resulting  multibyte  characters  are
          written up to (but  not including) the terminating null
          byte.  If a precision is  specified, no more bytes than
          the  number  specified  are  written,  but  no  partial
          multibyte  characters  are   written.   Note  that  the
          precision determines  the number of bytes  written, not
          the number of wide characters or screen positions.  The
          array must  contain a terminating null  wide character,
          unless a precision is given and it is so small that the
          number of  bytes written exceeds  it before the  end of
          the array is reached.

    + =n= \\
      The number of characters written  so far is stored into
          the integer  pointed to by the  corresponding argument.
          That argument shall be an  int *, or variant whose size
          matches  the   (optionally)  supplied   integer  length
          modifier.  No  argument is converted.  The  behavior is
          undefined if the  conversion specification includes any
          flags, a field width, or a precision.

    + =%= \\
      A  '%'  is written.   No  argument  is converted.   The
          complete conversion specification is '%%'.



* C99 Enhancement
:PROPERTIES:
:CUSTOM_ID: h:7035809D-1B2D-4AEE-8F56-3FEE5989B218
:END:

为了让代码可移植性更好，C99 提供了两个极为有用的头文件。

** stdint.h
:PROPERTIES:
:CUSTOM_ID: h:1745EF37-A6EF-475D-9B60-61F92A85EA30
:END:

该文件提供了诸如 =int32=, =uint32=, =uint16= 等等类型的定义

** inttypes.h
:PROPERTIES:
:CUSTOM_ID: h:ED40E9D1-1A26-4510-9355-B0F387D8B2A3
:END:

该文件提供了若干宏用于格式化输出，可以用于 =printf= 以及 =scanf= 。

可以参考这里：
 [[http://en.wikipedia.org/wiki/C_data_types#inttypes.h]]
