#+TITLE: The efficiency of different cpp constructs
#+AUTHOR: Yang, Ying-chao
#+EMAIL:  yangyingchao[at]gmail[dot]com
#+KEYWORDS: constructs cpp
#+CATEGORY: Development
#+DESCRIPTION: (nil)
#+OPTIONS:  ^:nil toc:2 H:3 \n:nil ::t |:t ^:{} -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align nodlcheck oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+LANGUAGE:   en
#+EXCLUDE_TAGS: noexport


* 存储类型

C++ 中，变量和对象根据不同的声明，会被存放于内存的不同段里。这些存储方式，会对 Cache
产生一些影响：如果这些变量和对象过于分散，将会影响 cache。

** Stack:

*** Who

Variables and objects declared inside a function are stored on the stack, except for the cases described in the sections below.

*** Explain:

The stack is the most efficient memory space to store data because the same range of
memory addresses is reused again and again. If there are no big arrays, then it is
almost certain that this part of the memory is mirrored in the level-1 data cache, where it is accessed quite fast.

*** Lesson

The lesson we can learn from this is that all variables and objects should preferably
be declared inside the function in which they are used.

** Global or static storage

*** Who

Variables that are declared outside of any function are called global variables. They
can be accessed from any function. Global variables are stored in a static part of the
memory. The static memory is also used for variables declared with the static keyword,
for floating point constants, string constants, array initializer lists, switch
statement jump tables, and virtual function tables.

*** Explain
