#+TITLE: helm xgtags
#+AUTHOR: Yang, Ying-chao
#+EMAIL:  yangyingchao[at]gmail[dot]com
#+KEYWORDS: (nil)
#+CATEGORY: (nil)
#+DESCRIPTION: (nil)
#+OPTIONS:  ^:nil toc:2 H:3 \n:nil ::t |:t ^:{} -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align nodlcheck oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+LANGUAGE:   en
#+EXCLUDE_TAGS: noexport

helm-xgtags is helm interface for [[http://www.emacswiki.org/emacs/xgtags.el][xgtags]].

* Why [[https://github.com/yangyingchao/helm-xgtags][helm-xgtags]]?

[[http://www.emacswiki.org/emacs/xgtags.el][xgtags]] is great, but when there are multiple candidates of definitions or references,
we have to use =C-s= to locate/find specified file in =xgtags-select-mode=.

[[https://github.com/syohex/emacs-helm-gtags][helm-gtags]], on the other hand, provided better interaction, but I don't like its
colors/faces, and some functionality are missing, for example, jump to next/previous
tag.

So I modified xgtags a little and make it integrated with [[https://github.com/emacs-helm/helm][helm]].

Compared with =xgtags=, it can:

- Select/Filter tags/files with help of helm.
- Press any key in =helm-xgtags-select-mode= to activate helm.
- =helm-xgtags-parse-file= can preselect tag/function of current line.
- Update database when file is saved

* Installation


 To use helm-xgtags copy this file to some place where emacs can find it,
 if necessary add the path you chose to the load-path variable. In
 your .emacs add the line

 #+BEGIN_SRC emacs-lisp -r
(require 'helm-xgtags)
 #+END_SRC


 In any buffer you can now toggle helm-xgtags-mode by calling the
 interactive command with same name. Since this is a bit annoying,
 you might choose to turn it on for some specific modes. For c-mode
 you can add something like the following snippet to your .emacs
 file. Other modes provide similar hooks.

 #+BEGIN_SRC emacs-lisp -r
   (add-hook 'c-mode-common-hook
             (lambda ()
          (helm-xgtags-mode 1)))

 #+END_SRC


 After that you can use the predefined keybindings to query your
 GLOBAL database. Call 'describe-function RE'S helm-xgtags-mode' to get an
 overview of those bindings.

* Customization

It is recommended to use =Easy Csutomization= to customize =helm-xgtags=.
Simple execute =customize=, and search for =helm-xgtags=.
