#+TITLE: Memory Allocator of Sqlite
#+AUTHOR: Yang, Ying-chao
#+EMAIL:  yangyingchao[at]gmail[dot]com
#+KEYWORDS: Memory, Allocator, Sqlite
#+CATEGORY: (nil)
#+DESCRIPTION: (nil)
#+OPTIONS:  ^:nil toc:2 H:3 \n:nil ::t |:t ^:{} -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align nodlcheck oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+LANGUAGE:   en
#+HTML_HEAD: <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    http://yangyingchao.github.io
#+LINK_HOME:  http://yangyingchao.github.io
#+EXCLUDE_TAGS: noexport

* Sqlite 中的内存管理

=sqlite3_initialize()= 会检查和设置 Sqlite 的内存分配方案。设置通过
=sqlite3MallocInit()= 来完成。 =sqlite3MallocInit()=  会检查全局设置中的内存操作指
针是否为空，是的话则使用 =sqlite3MemSetDefault()= 来采用默认设置。

Sqlite 提供了六种分配方式，分别为 =mem0=, =mem1=, =mem2=, =mem3=, =mem5= 以及针对
win32 的 =winMemMethods= ，具体使用哪一个在编译
期通过宏来决定。

相关的宏包括：

 * =SQLITE_ZERO_MALLOC=

   这个宏启用的时候，会使用 =mem0= ，所有内存分配都会返回空指针。也许只是用来测试的？

 * =SQLITE_SYSTEM_MALLOC=

   该宏启用使用， =mem1= 被启用，会使用标准 C 提供的 =malloc()= 来分配内存。

   此外，如果编译期没有指定内存分配器，Sqlite 默认将此启用。

 * =SQLITE_MEMDEBUG=

   对应 =mem2= ，同样使用系统的 =malloc()= ，但包含一些额外的信息用于调试内存分配。

 * =SQLITE_WIN32_MALLOC=

   对应 =winMemMethods= ，将启用 Win32 native heap API。

 * =SQLITE_ENABLE_MEMSYS3=

   对应 =mem3= ，所有内存都从预先传入的堆中分配，不会使用 =malloc= 。

 * =SQLITE_ENABLE_MEMSYS5=

   对应 =mem5= ，所有内存都从预先传入的堆中分配，不会使用 =malloc= 。

   *TOOD：* 与 =mem3= 区别？？？

如果编译期没有指定内存分配方式， =mem1= 将被采用：

#+BEGIN_SRC c -r -n
#if defined(SQLITE_SYSTEM_MALLOC) \
  + defined(SQLITE_WIN32_MALLOC) \
  + defined(SQLITE_ZERO_MALLOC) \
  + defined(SQLITE_MEMDEBUG)>1
# error "Two or more of the following compile-time configuration options\
 are defined but at most one is allowed:\
 SQLITE_SYSTEM_MALLOC, SQLITE_WIN32_MALLOC, SQLITE_MEMDEBUG,\
 SQLITE_ZERO_MALLOC"
#endif
#if defined(SQLITE_SYSTEM_MALLOC) \
  + defined(SQLITE_WIN32_MALLOC) \
  + defined(SQLITE_ZERO_MALLOC) \
  + defined(SQLITE_MEMDEBUG)==0
# define SQLITE_SYSTEM_MALLOC 1
#endif
#+END_SRC

上述的各种方案均通过各自提供的 =sqlite3MemSetDefault()= 来设置函数指针：

#+BEGIN_SRC c -r -n
  void sqlite3MemSetDefault(void){
      static const sqlite3_mem_methods defaultMethods = {
          sqlite3MemMalloc,
          sqlite3MemFree,
          sqlite3MemRealloc,
          sqlite3MemSize,
          sqlite3MemRoundup,
          sqlite3MemInit,
          sqlite3MemShutdown,
          0
      };
      sqlite3_config(SQLITE_CONFIG_MALLOC, &defaultMethods);
  }
#+END_SRC


* Mem1 -- Standard Memory Management

=mem1= 中的内存操作函数是对 =malloc/free= 的封装。

如果系统提供了 =malloc.h= ，则可以通过系统提供的 API 来获取某一已经分配的
空间的大小， =sqlite3_mem_methods= 中定义的所有方法都是简单调用。否则的话，
需要对 =malloc/free= 做一些封装。

 * =sqlite3MemMalloc=
  分配内存时，多分配了一些字节，并用最高的 8 个字节来保存分配的 size，
  并将指针加 8 后返回。

   #+BEGIN_SRC c -r -n
   /*
   ,** Round up a number to the next larger multiple of 8.  This is used
   ,** to force 8-byte alignment on 64-bit architectures.
   ,*/
   #define ROUND8(x)     (((x)+7)&~7)

   static void *sqlite3MemMalloc(int nByte){
       sqlite3_int64 *p;
       assert( nByte>0 );
       nByte = ROUND8(nByte);
       p = SQLITE_MALLOC( nByte+8 );
       if( p ){
           p[0] = nByte;
           p++;
       }else{/**/}
       return (void *)p;
   }
   #+END_SRC

 * =sqlite3MemFree=
   =sqlite3MemFree=  的反向操作，指针减 8 之后删除，删除即可：

   #+BEGIN_SRC c -r -n
     static void sqlite3MemFree(void *pPrior){
       sqlite3_int64 *p = (sqlite3_int64*)pPrior;
       assert( pPrior!=0 );
       p--;
     }
   #+END_SRC

* Mem2 -- Standard Memory with Debug Info

=mem2= 同样采用系统的 =malloc/free/realloc= 来分配内存，但在其基础上增加了额外的调试信息，可
以帮助检测内存泄漏 *(HOW?)* 和内存的其他错误。

** =sqlite3MemMalloc()=

每块内存的布局如下：

#+BEGIN_SRC ditaa :file ../assets/img/mem2_allocation.png  :cmdline -r -s 1.5
  +-------+---------------------+--------------+-------------+-----------+
  | Title |  backtrace pointers |  MemBlockHdr |  allocation |  EndGuard |
  +-------+---------------------+--------------+-------------+-----------+
#+END_SRC

 * Title \\
   Title 是一个用户设置的字符串(up to 100 bytes)，其值通过 =sqlite3MemdebugSettitle()=
   设置到全局的 [[static_mem][=mem=]] 静态变量中，并在 =sqlite3MemMalloc()= 中拷贝至每一个 block 中，
   并在 =sqlite3MemdebugDump()= 中输出到指定文件里。

 * Backtrace Pointers\\
   包含若干 backtrace 的指针，backtrace 的数量由 =mem.nBacktrace= 指定。

 * =MemBlockHdr= \\

  #+BEGIN_SRC c -r -n
    struct MemBlockHdr {
      i64 iSize;                          /* Size of this allocation */
      struct MemBlockHdr *pNext, *pPrev;  /* Linked list of all unfreed memory */
      char nBacktrace;                    /* Number of backtraces on this alloc */
      char nBacktraceSlots;               /* Available backtrace slots */
      u8 nTitle;                          /* Bytes of title; includes '\0' */
      u8 eType;                           /* Allocation type code */
      int iForeGuard;                     /* Guard word for sanity */
    };

  #+END_SRC

 * allocation \\
   =allocation= 是 =mem2= 的用户能真正使用的内存块。改块在分配成功后会用随机数
   来填充。

 * EndGuard \\
   =EndGuard= 与 =MemBlockHdr.iForeGuard= 分别作为 =allocation= 的前后标记，
   将会在若干检查中用到，其值分别为：

   #+BEGIN_SRC c -r -n
     /*
      ,** Guard words
      ,*/
     #define FOREGUARD 0x80F5E153
     #define REARGUARD 0xE4676B53
   #+END_SRC

 * =mem=  \\
   =mem2= 中另有一个静态的 =mem= 变量， 其中有指向分配的 =MemBlockHdr= 指针：

  #+BEGIN_SRC c -r -n
  /*
  ,** All of the static variables used by this module are collected
  ,** into a single structure named "mem".  This is to keep the
  ,** static variables organized and to reduce namespace pollution
  ,** when this module is combined with other in the amalgamation.
  ,*/
  static struct { (ref:static_mem)

      /*
      ,** Mutex to control access to the memory allocation subsystem.
      ,*/
      sqlite3_mutex *mutex;

      /*
      ,** Head and tail of a linked list of all outstanding allocations
      ,*/
      struct MemBlockHdr *pFirst;
      struct MemBlockHdr *pLast;

      /*
      ,** The number of levels of backtrace to save in new allocations.
      ,*/
      int nBacktrace;
      void (*xBacktrace)(int, int, void **);

      /*
      ,** Title text to insert in front of each block
      ,*/
      int nTitle;        /* Bytes of zTitle to save.  Includes '\0' and padding */
      char zTitle[100];  /* The title text */

      /*
      ,** sqlite3MallocDisallow() increments the following counter.
      ,** sqlite3MallocAllow() decrements it.
      ,*/
      int disallow; /* Do not allow memory allocation */

      /*
      ,** Gather statistics on the sizes of memory allocations.
      ,** nAlloc[i] is the number of allocation attempts of i*8
      ,** bytes.  i==NCSIZE is the number of allocation attempts for
      ,** sizes more than NCSIZE*8 bytes.
      ,*/
      int nAlloc[NCSIZE];      /* Total number of allocations */
      int nCurrent[NCSIZE];    /* Current number of allocations */
      int mxCurrent[NCSIZE];   /* Highwater mark for nCurrent */

  } mem;
  #+END_SRC

  #+BEGIN_SRC dot :file ../assets/img/mem_2_mem.png :cmdline -Kdot -Tpng
    digraph Name {
        node [fontsize=12 fontname=Courier style=filled shape=record];
        edge[color="#666666" style=dashed arrowhead=open tailclip=true];
        // rankdir=LR;

        //XXX: Place to put subgraphs
        node_mem[shape=record
                label="{<f0> mem |\
    +mutex &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : sqlite3_mutex *\l\
    +nBacktrace &#32;&#32;&#32;&#32;&#32; : int\l\
    +nTitle &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : int\l\
    +zTitle &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : char []\l\
    +disallow &#32;&#32;&#32;&#32;&#32;&#32;&#32; : int\l\
    +nAlloc &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : int []\l\
    +nCurrent &#32;&#32;&#32;&#32;&#32;&#32;&#32; : int []\l\
    +mxCurrent &#32;&#32;&#32;&#32;&#32;&#32; : int []\l\
    +xBacktrace (...) : void\l\
    |\
    <f1>+pFirst &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : struct MemBlockHdr *\l\
    |\
    <f2>+pLast &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : struct MemBlockHdr *\l\
    }"];

    node_mem:f1->node_MemBlockHdr1;
    node_mem:f2->node_MemBlockHdr3;

    subgraph  {
        color=invis;
        style=filled;
        rank=same;
        node_MemBlockHdr1[shape=record
                label="{<f0> MemBlockHdr|\
    +iSize &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : i64\l\
    +pNext &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : struct MemBlockHdr *\l\
    +pPrev &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : struct MemBlockHdr *\l\
    +nBacktrace &#32;&#32;&#32;&#32;&#32; : char\l\
    +nBacktraceSlots  : char\l\
    +nTitle &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : u8\l\
    +eType &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : u8\l\
    +iForeGuard &#32;&#32;&#32;&#32;&#32; : int\l\
    }"];

    node_MemBlockHdr2[shape=record
                label="{<f0> MemBlockHdr|\
    +iSize &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : i64\l\
    +pNext &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : struct MemBlockHdr *\l\
    +pPrev &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : struct MemBlockHdr *\l\
    +nBacktrace &#32;&#32;&#32;&#32;&#32; : char\l\
    +nBacktraceSlots  : char\l\
    +nTitle &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : u8\l\
    +eType &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : u8\l\
    +iForeGuard &#32;&#32;&#32;&#32;&#32; : int\l\
    }"];

    node_MemBlockHdr3[shape=record
                label="{<f0> MemBlockHdr |\
    +iSize &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : i64\l\
    +pNext &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : struct MemBlockHdr *\l\
    +pPrev &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : struct MemBlockHdr *\l\
    +nBacktrace &#32;&#32;&#32;&#32;&#32; : char\l\
    +nBacktraceSlots  : char\l\
    +nTitle &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : u8\l\
    +eType &#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32;&#32; : u8\l\
    +iForeGuard &#32;&#32;&#32;&#32;&#32; : int\l\
    }"];

    }


    node_MemBlockHdr1->node_MemBlockHdr2[dir=both minlen=6];
    node_MemBlockHdr2->node_MemBlockHdr3[dir=both minlen=6];

    }
  #+END_SRC

** sqlite3MemdebugDump()

用于将已经分配的资源 dump 到指定的文件中。

* Mem3

=mem3= 不使用 =malloc/free= ，而是从预先分好的内存中（ =sqlite3GlobalConfig.pHeap= ）
动态规划。整个 Heap 被分成 N 个 chunk ( N = size_of_Heap/sizeof(Mem3Block)):

#+BEGIN_SRC c -r -n
  typedef struct Mem3Block Mem3Block;
  struct Mem3Block {
      union {
          struct {
              u32 prevSize;   /* Size of previous chunk in Mem3Block elements */
              u32 size4x;     /* 4x the size of current chunk in Mem3Block elements */
          } hdr;
          struct {
              u32 next;       /* Index in mem3.aPool[] of next free chunk */
              u32 prev;       /* Index in mem3.aPool[] of previous free chunk */
          } list;
      } u;
  };
#+END_SRC

所有全局信息存于静态变量 =mem3= 中：

#+BEGIN_SRC c -r -n
  static SQLITE_WSD struct Mem3Global {
      /*
      ,** Memory available for allocation. nPool is the size of the array
      ,** (in Mem3Blocks) pointed to by aPool less 2.
      ,*/
      u32 nPool;
      Mem3Block *aPool;

      /*
      ,** True if we are evaluating an out-of-memory callback.
      ,*/
      int alarmBusy;

      /*
      ,** Mutex to control access to the memory allocation subsystem.
      ,*/
      sqlite3_mutex *mutex;

      /*
      ,** The minimum amount of free space that we have seen.
      ,*/
      u32 mnMaster;

      /*
      ,** iMaster is the index of the master chunk.  Most new allocations
      ,** occur off of this chunk.  szMaster is the size (in Mem3Blocks)
      ,** of the current master.  iMaster is 0 if there is not master chunk.
      ,** The master chunk is not in either the aiHash[] or aiSmall[].
      ,*/
      u32 iMaster;
      u32 szMaster;

      /*
      ,** Array of lists of free blocks according to the block size
      ,** for smaller chunks, or a hash on the block size for larger
      ,** chunks.
      ,*/
      u32 aiSmall[MX_SMALL-1];   /* For sizes 2 through MX_SMALL, inclusive */
      u32 aiHash[N_HASH];        /* For sizes MX_SMALL+1 and larger */
  } mem3 = { 97535575 };
#+END_SRC

分配内存时，优先从 =mem3->aiSmall= 或者 =mem3->aiHash= 中寻找何时的 chunk，如果找不到，
则从 =mem3->aPool= 中分配，并设置 block header.

回收内存时，将 chunk 链入 =mem3->aiSmall=  或者 =mem3->aiHash= 。

* Mem5
