#+TITLE: EXT2 笔记
#+AUTHOR: Yang, Ying-chao
#+EMAIL:  yangyingchao[at]gmail[dot]com
#+KEYWORDS: EXT2, FileSystem
#+CATEGORY: kernel
#+DESCRIPTION: (nil)
#+OPTIONS:  ^:nil toc:1 H:3 \n:nil ::t |:t ^:{} -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align nodlcheck oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+LANGUAGE:   en
#+HTML_HEAD: <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LINK_UP:    http://yangyingchao.github.io
#+LINK_HOME:  http://yangyingchao.github.io
#+EXCLUDE_TAGS: noexport

记录一下 Ext2 文件系统相关的一些知识。

* Specification

 * Blocks

 磁盘或文件被划分成块 （Blocks），块大小在文件系统创建时指定，可为 1024, 2048, 4096 或
 8192。较小的 block size 意味着单个文件浪费的空间更小，但也意味着内核需要管理更多的块，
 从而在管理和统计上花费更多的资源。

 * Block Groups

   + Blocks are clustered into block groups in order to reduce fragmentation
     and minimise the amount of head seeking when reading a large amount of consecutive data.
   + Information about each block group is kept in a
     descriptor table stored in the block(s) immediately after the superblock.
   + Two blocks near the start of each group are reserved for the block usage
     bitmap and the inode usage bitmap which show which blocks and inodes
     are in use.
   + The block(s) following the bitmaps in each block group are designated
     as the inode table for that block group and the remainder are the data
     blocks
   + The block allocation algorithm attempts to allocate data blocks
     in the same block group as the inode which contains them.

   #+BEGIN_SRC ditaa :file ../assets/img/name.png  :cmdline -r -s 0.8

   +-----------+-------------------+---------------+
   | SuperBlock| Block Group Infor |  Block Group1 |
   +---------------+---------------+---------------+
   |  Block Group1 | Block group 2 |  ........     |
   +---------------+---------------+---------------+

   /                 \
   /                   \
   /                     \
   /                       \
   /                         \
   /                           \
   /                             \
   /                               \
   /                                 \
   +----+----+----+------+------+----------+
   | BM | IM | IT | BLK1 | BLK2 | .....    |
   +----+----++---+------+------+----------+

   BM --  Bblock BitMap
   IM --  INode BitMap
   IT --  INode Table
   #+END_SRC

 * Superblock

   超块中保存了文件系统的所有配置信息。超块信息保存在设备起始点的1024字节偏移处，该信
   息在文件系统挂载时被内核读取。此外，超块信息还有若干备份，用户可以选择将其保存在所
   有的 BlockGroup 中，或者选择将其保存在 0，1，以及 2 的 3，5，7次冥的超块中。

   超块中保存的数据包括：
   - 文件系统中 iNode 与 block 的数量以及使用情况
   - 每个 block group 中的 inode 和 block 数量
   - 文件系统上一次被挂载和修改的时间
   - 文件系统的创建时间和文件系统的版本信息。

   超块中的所有信息均以小端格式写入磁盘。

 * Inodes (Index Nodes)
   索引节点是 Ext2 文件系统中的一个基础概念，文件系统的每个对象都通过一个 inode 来表示。
   inode 中通过指针指向包含对象内容的 blocks，以及相关的除名字之外的所有元数据 (metadata) 。

 * Directories

   目录同文件一样，也是包含有 inode 的文件系统对象。不同之处在于，目录其实是一个特殊格式的文
   件，它里面包含了若干属于该目录的文件名字和与之对应的 inode number。

 * Special files

   - Symbolic Links: 如果符号链接小于 60 字节，则其数据会占用若干应该指向 block 的指针，从而
     将数据存储到 inode 里面，避免了浪费额外的 block。

   - 字符设备与块设备都直接将数据存到 inode 中，没有额外的 block，与小型的符号链接一样。

* Module Initialization

 #+BEGIN_SRC dot :file ../assets/img/mbcache.png :cmdline -Kdot -Tpng
   digraph Name {
       node [fontsize=12 fontname=Courier style=filled shape=record];
       edge[color="#666666" style=dashed arrowhead=open tailclip=true];
       // rankdir=LR;

       //XXX: Place to put subgraphs
   node_mb_cache[shape=record
               label="{<f0> mb_cache |\
   +c_cache_list &#32; : struct list_head\l\
   +c_name &#32;&#32;&#32;&#32;&#32;&#32;&#32; : char *\l\
   +c_entry_count  : atomic_t\l\
   +c_max_entries  : int\l\
   +c_bucket_bits  : int\l\
   +c_entry_cache  : struct kmem_cache *\l\
   +c_block_hash &#32; : struct list_head *\l\
   +c_index_hash &#32; : struct list_head *\l\
   |\
   }"];


   node_mb_cache_entry[shape=record
               label="{<f0> mb_cache_entry |\
   +e_lru_list &#32;&#32; : struct list_head\l\
   +e_cache &#32;&#32;&#32;&#32;&#32; : struct mb_cache *\l\
   +e_used &#32;&#32;&#32;&#32;&#32;&#32; : unsigned short\l\
   +e_queued &#32;&#32;&#32;&#32; : unsigned short\l\
   +e_bdev &#32;&#32;&#32;&#32;&#32;&#32; : struct block_device *\l\
   +e_block &#32;&#32;&#32;&#32;&#32; : sector_t\l\
   +e_block_list  : struct list_head\l\
   +e_index &#32;&#32;&#32;&#32;&#32; : struct \l\
   |\
   }"];

   }
 #+END_SRC