#+TITLE: How to update a GitHub forked repository
#+AUTHOR: Yang, Ying-chao
#+EMAIL:  yangyingchao[at]gmail[dot]com
#+KEYWORDS: git
#+CATEGORY: git
#+DESCRIPTION: (nil)
#+OPTIONS:  ^:nil toc:2 H:3 \n:nil ::t |:t ^:{} -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align nodlcheck oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+LANGUAGE:   en
#+EXCLUDE_TAGS: noexport

Reposted from:
http://stackoverflow.com/questions/7244321/how-to-update-a-github-forked-repository

 * *Q:*

 I recently forked a project and applied several fixes. I then created a pull request which was then accepted.

A few days later another change was made by another contributor. So my fork doesn't contain that change... How can I get that change into my fork?

Do I need to delete and re-create my fork when I have further changes to contribute? Or is there an update button?


 * *A:*

In your local clone of your forked repository, you can add the original GitHub repository as a "remote". ("Remotes" are like nicknames for the URLs of repositories - origin is one, for example.) Then you can fetch all the branches from that upstream repository, and rebase your work to continue working on the upstream version. In terms of commands that might look like:

#+BEGIN_SRC sh
  # Add the remote, call it "upstream":

  git remote add upstream https://github.com/whoever/whatever.git

  # Fetch all the branches of that remote into remote-tracking branches,
  # such as upstream/master:

  git fetch upstream

  # Make sure that you're on your master branch:

  git checkout master

  # Rewrite your master branch so that any commits of yours that
  # aren't already in upstream/master are replayed on top of that
  # other branch:

  git rebase upstream/master

#+END_SRC


If you don't want to rewrite the history of your master branch, (for example because other people may have cloned it) then you should replace the last command with git merge upstream/master. However, for making further pull requests that are as clean as possible, it's probably better to rebase.

Update: If you've rebased your branch onto upstream/master you may need to force the push in order to push it to your own forked repository on GitHub. You'd do that with:

git push -f origin master
You only need to use the -f the first time after you've rebased.