#+TITLE: Linux:How To Identify Server ECC Memory Modules
#+AUTHOR: Yang, Ying-chao
#+EMAIL:  yangyingchao@gmail.com
#+OPTIONS:    H:3 num:nil toc:t \n:nil ::t |:t ^:nil -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align nodlcheck oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+LANGUAGE:   en
#+EXCLUDE_TAGS: noexport
#+KEYWORDS: memory ecc
#+CATEGORY: Linux
#+DESCRIPTION: (nil)

#+BEGIN_HTML
  <span class="drop_cap">H</span>ow do I identify Linux server ECC memory modules from a shell prompt?<br> <span id="more-1005"></span><br> You need to count the chips on the module. If memory module has 9 chips per sides, it is ECC memory (EDAC protected memory). It may or may not be registered. If the memory module has 8 chips per side, it is not ECC memory modules.</p><p></p><center><script async="" src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>  <ins class="adsbygoogle" style="display:inline-block;width:336px;height:280px" data-ad-client="ca-pub-7825705102693166" data-ad-slot="2404767461"></ins> <script>(adsbygoogle = window.adsbygoogle || []).push({});</script><p></p></center><p></p><p>You can get this information by visiting your BIOS setup menu. Another option is to use <a href="http://www.cyberciti.biz/tips/querying-dumping-bios-from-linux-command-prompt.html">dmidecode command to dump bios memory information</a> from a shell prompt:<br> <code># dmidecode --type 16</code></p><pre># dmidecode 2.11
  SMBIOS 2.5 present.
  Handle 0x0016, DMI type 16, 15 bytes
  Physical Memory Array
      Location: System Board Or Motherboard
      Use: System Memory
      Error Correction Type: <span style="color: rgb(255, 0, 0);">Single-bit ECC</span>
      Maximum Capacity: 64 GB
      Error Information Handle: Not Provided
      Number Of Devices: 8
  </pre><p>To see memory speed and other information, enter:<br> <code># dmidecode --type memory</code></p>
#+END_HTML


Repost from: http://www.cyberciti.biz/faq/ecc-memory-modules/