#+TITLE: ssh rsa not working
#+AUTHOR: Yang, Ying-chao
#+EMAIL:  yangyingchao@gmail.com
#+OPTIONS:    ^:nil H:3 num:nil toc:t \n:nil ::t |:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc
#+STARTUP:    align nodlcheck oddeven lognotestate
#+SEQ_TODO:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+TAGS:       Write(w) Update(u) Fix(f) Check(c) noexport(n)
#+LANGUAGE:   en
#+EXCLUDE_TAGS: noexport
#+KEYWORDS: ssh
#+CATEGORY: Utils
#+DESCRIPTION: (nil)


Make sure the permissions on the ~/.ssh directory and its contents are
proper. When I first set up my ssh key auth, I didn't have the ~/.ssh folder
properly set up, and it yelled at me.

Your home directory ~, your ~/.ssh directory and the ~/.ssh/authorized_keys file on
the remote machine must be writable only by you: rwx------ and rwxr-xr-x are fine,
but rwxrwx--- is no good¹, even if you are the only user in your group (if you
prefer numeric modes: 700 or 755, not 775).

If ~/.ssh or authorized_keys is a symbolic link, the canonical path (with symbolic
links expanded) is checked.

Your ~/.ssh/authorized_keys file (on the remote machine) must be readable (at least
400), but you'll need it to be also writable (600) if you will add any more keys
to it.

Your private key file (on the local machine) must be readable and writable only by
you: rw-------, i.e. 600.

Also, if SELinux is set to enforcing, you may need to run restorecon -R -v ~/.ssh
(see e.g. Ubuntu bug 965663 and Debian bug report #658675; this is patched in
CentOS 6).
